[package]
name = "iot-toolbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.43"
eframe = "0.33.3"
egui = "0.33.3"
serialport = "4.8.1"
tokio = { version = "1", features = ["rt-multi-thread", "time"] }
tokio-modbus = "0.17.0"
